### ISSUE TITLE
[Errno 2] No such file or directory: '/plugins'

### ISSUE THREAD

**Issue by sergeifilippov** [raffaele-forte/climber#2]
1. After installing all dependencies
2. Run  `python climber.py --host host_ip --username username --ssh`
3. Enter `password`
4. Error :(

```bash
[i] Using driver: shell
[!] [Errno 2] No such file or directory: '/plugins'
```

```bash
$ tree plugins -L 1
plugins
├── file_systems
├── networking
├── operating_system
├── ssh
├── users
└── website

6 directories, 0 files
```
 
![error](https://cloud.githubusercontent.com/assets/123676/13692685/8d8e0eea-e7a8-11e5-8952-d30c637ac010.gif)

**Comment by gustavohenrique** [comment]
@sergeifilippov I fixed it and sent a pull request.
